name: Run longtail tests

on: push

jobs:
  build:
    strategy:  
      matrix:
        os: [ubuntu-latest, windows-latest, the-beast-mac]
        conf: [Release, Debug]
        target: [net8.0]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.conf }} - ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          8.0.x
        include-prerelease: true
        
    - name: Build
      run: dotnet build src/Longtail -c ${{ matrix.conf }} -f ${{ matrix.target }}
    
    - name: Test
      run: dotnet test tests/Longtail.Tests -c ${{ matrix.conf }} -f ${{ matrix.target }}

  package:
    needs: build
    runs-on: ubuntu-latest
    name: Nuget package
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          8.0.x
        include-prerelease: true

    - name: Package
      run: dotnet pack src/Longtail -c Release -o release/

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: NugetPackage
        path: release/*.nupkg

  publish:
    needs: package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Publish NuGet package

    steps:
      - name: Install .NET 8.0 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: preview

      - name: Download Nuget Package
        uses: actions/download-artifact@v3
        with:
          name: NugetPackage

      - name: Push nuget package
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/goalsgame --skip-duplicate 
